"""Typed client for the "rag" service — GENERATED by `vignemale gen`, do not edit."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from vignemale import call
from vignemale._genutil import validate_model

if TYPE_CHECKING:
    from rag.search import Question


def search(*, body: Question | dict) -> dict:
    """POST /search"""
    return call("rag", "search", body=body)
