"""`vignemale build`: builds the app's Docker image.

Two paths:

  - **fast (default)**: `FROM <base image>` + copy of the app's code. The
    `vignemale-python` base image contains the runtime (Rust core + SDK) ALREADY
    compiled and published in CI — building an app takes a few seconds, no Rust.
  - **--from-source**: compiles the Rust+PyO3 wheel in a builder stage (slow),
    useful in dev when the core is not yet published, or offline.

In both cases the final image is distroless (python 3.11, without shell or pip)
and embeds ONLY the runtime (pydantic + the .so): the runtime ships to prod with
pydantic as its only dependency.

The provider switch means the same image targets local or prod: `vignemale
deploy` will set the `VIGNEMALE_*` vars (managed DSN, Scaleway S3, secrets…); the
prod entry point (`python -m vignemale`) provisions nothing.
"""

import os
import shutil
import subprocess
import tempfile

# Default base image (pre-compiled runtime, published in CI on GHCR).
# Overridable via --base or VIGNEMALE_BASE_IMAGE.
DEFAULT_BASE_IMAGE = os.environ.get(
    "VIGNEMALE_BASE_IMAGE", "ghcr.io/vignemale-org/vignemale-python:latest"
)

# Parts of the vignemale source needed to compile the wheel (--from-source).
_SRC_PARTS = ["Cargo.toml", "Cargo.lock", "runtimes", "proto"]
# Excluded from the context copy (heavy / useless for the build).
_IGNORE = shutil.ignore_patterns(
    # NB: we keep vignemale_clients (generated clients) — they are REQUIRED at
    # runtime (services import them for inter-service call()).
    "target", ".venv", "__pycache__", "*.pyc", ".pytest_cache",
    "*.so", "dist", "*.egg-info", ".git",
)


def _sanitize(name: str) -> str:
    return "".join(c if c.isalnum() or c in "-_" else "-" for c in name.lower())


def _repo_root() -> str:
    """Root of the vignemale repo (Cargo workspace + runtimes/) — for --from-source."""
    override = os.environ.get("VIGNEMALE_SRC")
    if override:
        return os.path.abspath(override)
    # __file__ = .../cli/vignemale_cli/build.py → root = 3 levels above
    here = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if os.path.isfile(os.path.join(here, "Cargo.toml")) and os.path.isdir(
        os.path.join(here, "runtimes")
    ):
        return here
    raise SystemExit(
        "vignemale build --from-source: vignemale source not found (Cargo "
        "workspace + runtimes/). Set VIGNEMALE_SRC to the root of the vignemale repo."
    )


def _stage_app(app_path: str, ctx: str) -> str:
    """Copies the app's code into the context; returns its path INSIDE the image."""
    app_path = os.path.abspath(app_path)
    appdir = os.path.join(ctx, "app")
    if os.path.isdir(app_path):
        shutil.copytree(app_path, appdir, ignore=_IGNORE)
        return "/app"
    if os.path.isfile(app_path):
        os.makedirs(appdir)
        shutil.copy2(app_path, appdir)
        return "/app/" + os.path.basename(app_path)
    raise SystemExit(f"vignemale build: app not found: {app_path}")


def _stage_src(ctx: str) -> None:
    """Copies the vignemale source into the context (for --from-source)."""
    root = _repo_root()
    src = os.path.join(ctx, "src")
    os.makedirs(src)
    for part in _SRC_PARTS:
        s = os.path.join(root, part)
        d = os.path.join(src, part)
        if os.path.isdir(s):
            shutil.copytree(s, d, ignore=_IGNORE)
        elif os.path.isfile(s):
            shutil.copy2(s, d)
        else:
            raise SystemExit(f'vignemale build: "{part}" missing in {root}')


def _dockerfile_fast(container_app: str, base: str) -> str:
    return f"""# syntax=docker/dockerfile:1
# Generated by `vignemale build` — app on top of the pre-compiled runtime.
FROM {base}
COPY app/ /app/
ENTRYPOINT ["python", "-m", "vignemale", "{container_app}"]
"""


def _dockerfile_source(container_app: str) -> str:
    return f"""# syntax=docker/dockerfile:1
# Generated by `vignemale build --from-source` — compiles the runtime then the app.

# ---- stage 1: compile the Rust+PyO3 wheel (abi3, stripped+LTO) via maturin ----
FROM rust:1-bookworm AS builder
RUN apt-get update && apt-get install -y --no-install-recommends \\
        protobuf-compiler libprotobuf-dev patchelf python3 python3-dev python3-pip \\
    && rm -rf /var/lib/apt/lists/*
RUN pip install --break-system-packages --no-cache-dir 'maturin>=1.7,<2.0'
ENV PROTOC=/usr/bin/protoc
WORKDIR /build
COPY src/ /build/
RUN cd runtimes/python && maturin build --release --out /wheels

# ---- stage 2: install the runtime ALONE (pydantic + .so) in a flat directory ----
FROM python:3.11-slim-bookworm AS installer
COPY --from=builder /wheels/*.whl /tmp/
RUN pip install --no-cache-dir --target=/pylibs /tmp/*.whl \\
    && find /pylibs -type d -name __pycache__ -prune -exec rm -rf {{}} +

# ---- stage 3: final distroless image (python 3.11, without shell or pip) ----
FROM gcr.io/distroless/python3-debian12
WORKDIR /app
COPY --from=installer /pylibs /pylibs
COPY app/ /app/
ENV PYTHONPATH=/pylibs \\
    VIGNEMALE_ADDR=0.0.0.0:8080 \\
    VIGNEMALE_WORKERS=1
EXPOSE 8080
ENTRYPOINT ["python", "-m", "vignemale", "{container_app}"]
"""


def build(
    app_path: str,
    tag: str = None,
    print_only: bool = False,
    from_source: bool = False,
    base: str = None,
    platform: str = None,
    push: bool = False,
) -> str:
    base = base or DEFAULT_BASE_IMAGE
    if tag is None:
        name = os.path.splitext(os.path.basename(os.path.abspath(app_path)))[0]
        tag = f"vignemale-{_sanitize(name)}:latest"

    ctx = tempfile.mkdtemp(prefix="vignemale-build-")
    keep = print_only
    try:
        container_app = _stage_app(app_path, ctx)
        if from_source:
            _stage_src(ctx)
            dockerfile = _dockerfile_source(container_app)
        else:
            dockerfile = _dockerfile_fast(container_app, base)
        with open(os.path.join(ctx, "Dockerfile"), "w") as f:
            f.write(dockerfile)
        with open(os.path.join(ctx, ".dockerignore"), "w") as f:
            f.write("**/target\n**/.venv\n**/__pycache__\n**/.git\n")

        if print_only:
            print(dockerfile)
            print(f"# build context ready: {ctx}")
            print(f"# manual build:  docker build -t {tag} {ctx}")
            return tag

        if not shutil.which("docker"):
            raise SystemExit("vignemale build: Docker required (https://docker.com)")

        # buildx as soon as we target a platform (e.g. linux/amd64 for Scaleway
        # from an arm64 Mac) or push to the registry.
        if platform or push:
            cmd = ["docker", "buildx", "build"]
            if platform:
                cmd += ["--platform", platform]
            cmd += ["-t", tag, "--push" if push else "--load", ctx]
        else:
            cmd = ["docker", "build", "-t", tag, ctx]

        target = "pushing" if push else "building"
        where = f" ({platform})" if platform else ""
        src = "Rust release compilation, hang on" if from_source else f"on top of {base}"
        print(f'vignemale: {target} image "{tag}"{where} ({src})…', flush=True)
        r = subprocess.run(cmd)
        if r.returncode != 0:
            hint = ""
            if not from_source:
                hint = (
                    f"\n  (is the base image {base} reachable? "
                    "`docker login ghcr.io`, or `--from-source`)"
                )
            raise SystemExit(f"vignemale build: build failed{hint}")
        if push:
            print(f'vignemale: image "{tag}" pushed. Deploy:\n'
                  f"  vignemale deploy <app> --image {tag}", flush=True)
        else:
            print(
                f'vignemale: image "{tag}" ready.\n'
                f"  run:      docker run --rm -p 8080:8080 {tag}\n"
                f"  healthz:  curl localhost:8080/__vignemale/healthz",
                flush=True,
            )
        return tag
    finally:
        if not keep:
            shutil.rmtree(ctx, ignore_errors=True)
