"""`vignemale init [name]`: scaffold a Vignemale project ready to `run`.

Lays down a minimal starter layout — an `app.py` file with a typed `@api` (that
runs without any external infra), a `pyproject.toml` with `[tool.vignemale]`,
a `.gitignore` and a README. Goal: `pip install vignemale` → `vignemale
init my-app` → `vignemale run` in under a minute.

Without a name (or `.`): initializes the current directory. Never overwrites an
existing file (app.py / pyproject.toml) — it stops rather than clobbering.
"""

import os
import re
import sys


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower().strip()).strip("-")[:48]


APP_PY = '''\
"""{app} — a Vignemale app.

Infrastructure-from-Code: you write Python, Vignemale infers and provisions
the infra (local on `run`, cloud on `deploy`). Run:

    vignemale run app.py
    curl 127.0.0.1:8080/hello
    curl -X POST 127.0.0.1:8080/greet -d '{{"name":"Ada"}}'
"""

from pydantic import BaseModel

from vignemale import api, log


@api(method="GET", path="/hello")
def hello() -> dict:
    return {{"msg": "hi from {app} 👋"}}


class Who(BaseModel):
    name: str


@api(method="POST", path="/greet")
def greet(body: Who) -> dict:
    log.info("greet", name=body.name)
    return {{"msg": f"hello, {{body.name}}!"}}


# ── Next step: a database, no config ───────────────────────────────────────
# Uncomment this block — on `run`, Vignemale provisions a local Postgres all
# by itself (docker) and sets the DSN. In prod, the same code targets a managed
# database.
#
# from vignemale import SQLDatabase
#
# db = SQLDatabase("{slug}")
# db.execute("CREATE TABLE IF NOT EXISTS notes (id BIGSERIAL PRIMARY KEY, body TEXT)")
#
# @api(method="GET", path="/notes")
# def notes() -> dict:
#     return {{"notes": db.query("SELECT id, body FROM notes ORDER BY id")}}
'''

PYPROJECT = '''\
[project]
name = "{slug}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["vignemale>=0.1.3"]

[tool.vignemale]
# App name on Vignemale Cloud (git remote: /<app>.git).
app = "{slug}"
# mono  : a single container   ·   services : one container per service + gateway
topology = "mono"
'''

GITIGNORE = '''\
__pycache__/
*.py[cod]
.venv/
.env
# service clients generated by `vignemale gen`
vignemale_clients/
'''

README = '''\
# {app}

A [Vignemale](https://github.com/vignemale-org/vignemale) app — Infrastructure-from-Code in Python.

## Getting started

```bash
pip install vignemale
vignemale run app.py
```

```bash
curl 127.0.0.1:8080/hello
curl -X POST 127.0.0.1:8080/greet -d '{{"name":"Ada"}}'
```

## Deploy

```bash
vignemale login              # once
vignemale link {slug}         # link this repo to the project (created in the panel)
vignemale deploy             # push-to-deploy
```
'''


def init(name: str = ".", path: str = ".") -> int:
    # Target: `.` → current directory; otherwise a new <slug> subdirectory.
    if name in (".", ""):
        target = os.path.abspath(path)
        slug = _slug(os.path.basename(target))
    else:
        slug = _slug(name)
        if not slug:
            print("Invalid project name (letters, digits, dashes).", file=sys.stderr)
            return 1
        target = os.path.abspath(os.path.join(path, slug))
        os.makedirs(target, exist_ok=True)

    if not slug:
        print("Cannot infer an app name from the current directory; "
              "provide a name: vignemale init my-app", file=sys.stderr)
        return 1

    files = {
        "app.py": APP_PY.format(app=slug, slug=slug),
        "pyproject.toml": PYPROJECT.format(slug=slug),
        ".gitignore": GITIGNORE,
        "README.md": README.format(app=slug, slug=slug),
    }

    # We never overwrite app.py / pyproject.toml: a safeguard against an init in
    # an already existing project.
    for guard in ("app.py", "pyproject.toml"):
        if os.path.exists(os.path.join(target, guard)):
            print(f"{guard} already exists in {target} — aborting (nothing written).",
                  file=sys.stderr)
            return 1

    for rel, content in files.items():
        with open(os.path.join(target, rel), "w", encoding="utf-8") as f:
            f.write(content)

    where = "." if target == os.path.abspath(path) and name in (".", "") else slug
    print(f'vignemale: ✓ project "{slug}" created.')
    if where != ".":
        print(f"vignemale:   cd {where}")
    print("vignemale:   vignemale run app.py")
    return 0
