"""Runtime for the clients generated by `vignemale gen` (internal)."""

import importlib


def validate_model(module: str, name: str, data):
    """Re-types the response of an inter-service call into the declared model.

    The model's module is imported lazily: locally it is already loaded
    (no-op); deployed, the code is in the same image (monorepo).
    """
    if not isinstance(data, dict):
        return data
    cls = getattr(importlib.import_module(module), name)
    return cls.model_validate(data)
